#!/usr/bin/env python3
"""
读取 docs/个人信息配置模板.md 中的基础信息，生成 blog/site_config.py。
用法: python scripts/apply_config.py
"""

import re
import sys
from pathlib import Path

BLOG_DIR = Path(__file__).resolve().parent.parent
TEMPLATE_PATH = BLOG_DIR.parent / 'docs' / '个人信息配置模板.md'
OUTPUT_PATH = BLOG_DIR / 'site_config.py'


def parse_template(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    config = {}

    # 基本信息: - **姓名（AUTHOR）**：`值`
    for match in re.finditer(r'\*\*.*?（(\w+)）\*\*[：:]\s*`([^`]*)`', content):
        config[match.group(1)] = match.group(2)

    # 社交链接
    ICON_MAP = {
        'github': ('github', 'fab'), 'twitter': ('twitter', 'fab'), 'linkedin': ('linkedin', 'fab'),
        'rednote': ('pen-fancy', 'fas'), 'csdn': ('link', 'fas'), 'juejin': ('link', 'fas'),
        'zhihu': ('link', 'fas'), 'blog': ('blog', 'fas'), 'website': ('globe', 'fas'),
        'email': ('envelope', 'fas'), 'facebook': ('facebook', 'fab'), 'youtube': ('youtube', 'fab'),
        'instagram': ('instagram', 'fab'), 'stackoverflow': ('stack-overflow', 'fab'),
        'medium': ('medium', 'fab'), 'devto': ('dev', 'fab'), 'bilibili': ('link', 'fas'),
        'weibo': ('link', 'fas'), 'segmentfault': ('link', 'fas'),
    }
    social = []
    social_section = re.search(r'## 社交链接\n(.*?)(?=\n##)', content, re.DOTALL)
    if social_section:
        for line in social_section.group(1).strip().split('\n'):
            m = re.match(r'-\s*\*\*([\w]+)\*\*[：:]\s*`([^`]*)`', line)
            if m:
                name = m.group(1).lower()
                url = m.group(2).strip()
                icon, prefix = ICON_MAP.get(name, ('link', 'fas'))
                if url:
                    social.append((name, url, icon, prefix))
    config['SOCIAL'] = social

    # 关于我
    about_match = re.search(r'## 关于我（ABOUT_ME）\n\n.*?```\n(.*?)```', content, re.DOTALL)
    if about_match:
        config['ABOUT_ME'] = about_match.group(1).strip()

    # 技术栈 (捕获整行所有 `item`)
    tech_section = re.search(r'## 技术栈（TECH_STACK）\n\n.*?\n\n(.+)', content, re.DOTALL)
    if tech_section:
        items = re.findall(r'`([^`]+)`', tech_section.group(1))
        config['TECH_STACK'] = items

    return config


def generate_site_config(config):
    lines = ['# Auto-generated by scripts/apply_config.py', '']

    # 基本信息
    for key in ('AUTHOR', 'SITENAME', 'SITEDESCRIPTION'):
        val = config.get(key, '')
        lines.append(f"{key} = {repr(val)}")

    lines.append('')

    # 社交链接
    social = config.get('SOCIAL', [])
    if social:
        items = ', '.join(f"({repr(name)}, {repr(url)}, {repr(icon)}, {repr(prefix)})" for name, url, icon, prefix in social)
        lines.append(f"SOCIAL = ({items},)")
    else:
        lines.append('SOCIAL = ()')

    lines.append('')

    # 关于我
    about = config.get('ABOUT_ME', '')
    lines.append(f"ABOUT_ME = {repr(about)}")

    lines.append('')

    # 技术栈
    tech = config.get('TECH_STACK', [])
    items = ', '.join(repr(t) for t in tech)
    lines.append(f"TECH_STACK = ({items},)")

    lines.append('')

    # 版权年份
    lines.append("COPYRIGHT_YEAR = '2025'")

    return '\n'.join(lines) + '\n'


def main():
    if not TEMPLATE_PATH.exists():
        print(f"❌ 未找到模板文件: {TEMPLATE_PATH}")
        sys.exit(1)

    config = parse_template(TEMPLATE_PATH)

    if not config.get('AUTHOR'):
        print("❌ 模板中未填写基本信息，请先填写 docs/个人信息配置模板.md")
        sys.exit(1)

    content = generate_site_config(config)
    OUTPUT_PATH.write_text(content, encoding='utf-8')

    print(f"✅ 已生成 {OUTPUT_PATH.relative_to(BLOG_DIR.parent)}")
    print(f"   作者: {config.get('AUTHOR', '')}")
    print(f"   博客: {config.get('SITENAME', '')}")
    print(f"   社交: {len(config.get('SOCIAL', []))} 个")
    print(f"   技术栈: {len(config.get('TECH_STACK', []))} 项")


if __name__ == '__main__':
    main()
